server:
    port: 8081
spring:
    application.name: backend-resources
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://backend-auth:8086
